#!/bin/bash

WEB_SERVERS=( web1.langtrend.com )
WORKER_SERVERS=(
	worker1.langtrend.com
	worker2.langtrend.com
)

TMP_DIR=${TMP_DIR:-../tmp}

cd $( dirname $0 )

# Run tests
godep go test ../...
if [ $? -ne 0 ]; then
	echo "Error running tests"
	exit 1
fi

# Clean tmp dir
rm -rf "${TMP_DIR}" && mkdir -p "${TMP_DIR}"

# Build worker
godep go build -o "${TMP_DIR}/langtrend-worker" github.com/Miniand/langtrend/worker/main
if [ $? -ne 0 ]; then
	echo "Error building worker"
	exit 1
fi
echo "Built worker"

# Build web
godep go build -o "${TMP_DIR}/langtrend-web" github.com/Miniand/langtrend/web/main
if [ $? -ne 0 ]; then
	echo "Error building web"
	exit 1
fi
echo "Built web"

for i in "${WORKER_SERVERS[@]}"
do
	echo "Deploying to $i"

	# Stop services
	ssh "$i" "service langtrend-worker status | grep stop || service langtrend-worker stop"
	if [ $? -ne 0 ]; then
		echo "Error stopping worker server"
		exit 1
	fi

	# Upload binaries
	scp "${TMP_DIR}/langtrend-worker" "$i:/usr/bin/"
	if [ $? -ne 0 ]; then
		echo "Error uploading binary"
		exit 1
	fi

	# Start services
	ssh "$i" "service langtrend-worker start"
	if [ $? -ne 0 ]; then
		echo "Error starting service"
		exit 1
	fi
done

for i in "${WEB_SERVERS[@]}"
do
	echo "Deploying to $i"

	# Stop services
	ssh "$i" "service langtrend-web status | grep stop || service langtrend-web stop"
	if [ $? -ne 0 ]; then
		echo "Error stopping web server"
		exit 1
	fi

	# Upload binaries
	scp "${TMP_DIR}/langtrend-web" "$i:/usr/bin/"
	if [ $? -ne 0 ]; then
		echo "Error uploading binary"
		exit 1
	fi

	# Start services
	ssh "$i" "service langtrend-web start"
	if [ $? -ne 0 ]; then
		echo "Error starting service"
		exit 1
	fi
done

